### ISSUE TITLE
Proctored MCQ Week2:Quiz3 and Create Task review

### ISSUE THREAD

**Issue by christinlee367** [christinlee367/christinlee367.github.io#10]
# Graded by Sanvi Pal :  Score: 4.5/4.5
## Contents: 

- [x] Proctored MCQ Week2:Quiz3 
- [x] Create Task review Ticket

| Tasks | link | Description |
| --------------------- | -------------| ------------------|
| Quiz 3 : Github Pages|  [link](https://christinlee367.github.io/finalMCQ) | :heavy_check_mark: The quiz corrections are at this link. Please click on the label: "Link to Corrections(CLICK ME)" to find the question that you want to see that has been corrected. Click the right-hand corner of any of the corrections to go back to the top of the page. The table on the top is the summary of the scores and for which quiz. |
| Final Program Code | [link](https://docs.google.com/document/d/1M4VYnpY799KLqAGVW3r1h20HVxSe6nb0tfzDhQb8Zi4/edit?usp=sharing) | :heavy_check_mark: Here is the full length program code in a google document. This is also the same copy that was sent to college board. The code was done in HTML but there is javascript as indicated by the <script></script> labels. |
| Documented Questions | [link](https://docs.google.com/document/d/11iBHyZwRhJv1KAV-6ksIRwWnLkojwO7DqxR9wBiASV0/edit?usp=sharing) | ✔️ Here is the questions documented from 3a-3d. The entire word count is 657 words which is under 750-word max. The questions are written with attention to detail with care done over a span of hours. |
| Runtime |  [createTaskRunTime (1).mp4.zip](https://github.com/christinlee367/christinlee367.github.io/files/8612561/createTaskRunTime.1.mp4.zip) |:heavy_check_mark: Here is the runtime of the code in the form of a zip archive. The video is in total 52 seconds long and has captions on the top right hand corner. |

**Comment by sanvi1855544** [comment]
4.5/5

She gets a full score because I see signficant improvement from last week. Last week, she didn't demonstrate both calls in the video. This week's video and writeup have been updated to include the 3d point. The written part is well written because it mentions the algorithm, procedure, and lists (the three main components). If I was a AP reader I would give create task 6/6. The quiz score is lower that last quiz's but this is because their quiz had more algorithmic questions. The corrections are reflective so I didn't dock off point. Make sure to change study plan to practice more algorithm questions.
